# ## code to prepare `RDS` dataset goes here
#
# # LT
# LTHUAB1401 <- readr::read_rds("data-raw/RDS/LTHUAB1401.rds")
# LTHUAB1402 <- readr::read_rds("data-raw/RDS/LTHUAB1402.rds")
# LTHUAB1403 <- readr::read_rds("data-raw/RDS/LTHUAB1403.rds")
# LTHUAB1404 <- readr::read_rds("data-raw/RDS/LTHUAB1404.rds")
# LTHUAB1405 <- readr::read_rds("data-raw/RDS/LTHUAB1405.rds")
# LTHUAB1406 <- readr::read_rds("data-raw/RDS/LTHUAB1406.rds")
# LTHUAB1407 <- readr::read_rds("data-raw/RDS/LTHUAB1407.rds")
# LTHUAB1408 <- readr::read_rds("data-raw/RDS/LTHUAB1408.rds")
# LTHUAB1409 <- readr::read_rds("data-raw/RDS/LTHUAB1409.rds")
# LTHUAB1410 <- readr::read_rds("data-raw/RDS/LTHUAB1410.rds")
# LTHUAB1411 <- readr::read_rds("data-raw/RDS/LTHUAB1411.rds")
# LTHUAB1412 <- readr::read_rds("data-raw/RDS/LTHUAB1412.rds")
# LTHUAB1501 <- readr::read_rds("data-raw/RDS/LTHUAB1501.rds")
# LTHUAB1502 <- readr::read_rds("data-raw/RDS/LTHUAB1502.rds")
# LTHUAB1503 <- readr::read_rds("data-raw/RDS/LTHUAB1503.rds")
# LTHUAB1504 <- readr::read_rds("data-raw/RDS/LTHUAB1504.rds")
# LTHUAB1505 <- readr::read_rds("data-raw/RDS/LTHUAB1505.rds")
# LTHUAB1506 <- readr::read_rds("data-raw/RDS/LTHUAB1506.rds")
# LTHUAB1507 <- readr::read_rds("data-raw/RDS/LTHUAB1507.rds")
# LTHUAB1508 <- readr::read_rds("data-raw/RDS/LTHUAB1508.rds")
# LTHUAB1509 <- readr::read_rds("data-raw/RDS/LTHUAB1509.rds")
# LTHUAB1510 <- readr::read_rds("data-raw/RDS/LTHUAB1510.rds")
# LTHUAB1511 <- readr::read_rds("data-raw/RDS/LTHUAB1511.rds")
# LTHUAB1512 <- readr::read_rds("data-raw/RDS/LTHUAB1512.rds")
# LTHUAB1601 <- readr::read_rds("data-raw/RDS/LTHUAB1601.rds")
# LTHUAB1602 <- readr::read_rds("data-raw/RDS/LTHUAB1602.rds")
# LTHUAB1603 <- readr::read_rds("data-raw/RDS/LTHUAB1603.rds")
# LTHUAB1604 <- readr::read_rds("data-raw/RDS/LTHUAB1604.rds")
# LTHUAB1605 <- readr::read_rds("data-raw/RDS/LTHUAB1605.rds")
# LTHUAB1606 <- readr::read_rds("data-raw/RDS/LTHUAB1606.rds")
# LTHUAB1607 <- readr::read_rds("data-raw/RDS/LTHUAB1607.rds")
# LTHUAB1608 <- readr::read_rds("data-raw/RDS/LTHUAB1608.rds")
# LTHUAB1609 <- readr::read_rds("data-raw/RDS/LTHUAB1609.rds")
# LTHUAB1610 <- readr::read_rds("data-raw/RDS/LTHUAB1610.rds")
# LTHUAB1611 <- readr::read_rds("data-raw/RDS/LTHUAB1611.rds")
# LTHUAB1612 <- readr::read_rds("data-raw/RDS/LTHUAB1612.rds")
# LTHUAB1701 <- readr::read_rds("data-raw/RDS/LTHUAB1701.rds")
# LTHUAB1702 <- readr::read_rds("data-raw/RDS/LTHUAB1702.rds")
# LTHUAB1703 <- readr::read_rds("data-raw/RDS/LTHUAB1703.rds")
# LTHUAB1704 <- readr::read_rds("data-raw/RDS/LTHUAB1704.rds")
# LTHUAB1705 <- readr::read_rds("data-raw/RDS/LTHUAB1705.rds")
# LTHUAB1706 <- readr::read_rds("data-raw/RDS/LTHUAB1706.rds")
# LTHUAB1707 <- readr::read_rds("data-raw/RDS/LTHUAB1707.rds")
# LTHUAB1708 <- readr::read_rds("data-raw/RDS/LTHUAB1708.rds")
# LTHUAB1709 <- readr::read_rds("data-raw/RDS/LTHUAB1709.rds")
# LTHUAB1710 <- readr::read_rds("data-raw/RDS/LTHUAB1710.rds")
# LTHUAB1711 <- readr::read_rds("data-raw/RDS/LTHUAB1711.rds")
# LTHUAB1712 <- readr::read_rds("data-raw/RDS/LTHUAB1712.rds")
# LTHUAB1801 <- readr::read_rds("data-raw/RDS/LTHUAB1801.rds")
# LTHUAB1802 <- readr::read_rds("data-raw/RDS/LTHUAB1802.rds")
# LTHUAB1803 <- readr::read_rds("data-raw/RDS/LTHUAB1803.rds")
# LTHUAB1804 <- readr::read_rds("data-raw/RDS/LTHUAB1804.rds")
# LTHUAB1805 <- readr::read_rds("data-raw/RDS/LTHUAB1805.rds")
# LTHUAB1806 <- readr::read_rds("data-raw/RDS/LTHUAB1806.rds")
# LTHUAB1807 <- readr::read_rds("data-raw/RDS/LTHUAB1807.rds")
# LTHUAB1808 <- readr::read_rds("data-raw/RDS/LTHUAB1808.rds")
# LTHUAB1809 <- readr::read_rds("data-raw/RDS/LTHUAB1809.rds")
# LTHUAB1810 <- readr::read_rds("data-raw/RDS/LTHUAB1810.rds")
# LTHUAB1811 <- readr::read_rds("data-raw/RDS/LTHUAB1811.rds")
# LTHUAB1812 <- readr::read_rds("data-raw/RDS/LTHUAB1812.rds")
# LTHUAB1901 <- readr::read_rds("data-raw/RDS/LTHUAB1901.rds")
# LTHUAB1902 <- readr::read_rds("data-raw/RDS/LTHUAB1902.rds")
# LTHUAB1903 <- readr::read_rds("data-raw/RDS/LTHUAB1903.rds")
# LTHUAB1904 <- readr::read_rds("data-raw/RDS/LTHUAB1904.rds")
# LTHUAB1905 <- readr::read_rds("data-raw/RDS/LTHUAB1905.rds")
# LTHUAB1906 <- readr::read_rds("data-raw/RDS/LTHUAB1906.rds")
# LTHUAB1907 <- readr::read_rds("data-raw/RDS/LTHUAB1907.rds")
# LTHUAB1908 <- readr::read_rds("data-raw/RDS/LTHUAB1908.rds")
# LTHUAB1909 <- readr::read_rds("data-raw/RDS/LTHUAB1909.rds")
# LTHUAB1910 <- readr::read_rds("data-raw/RDS/LTHUAB1910.rds")
# LTHUAB1911 <- readr::read_rds("data-raw/RDS/LTHUAB1911.rds")
# LTHUAB1912 <- readr::read_rds("data-raw/RDS/LTHUAB1912.rds")
# LTHUAB2001 <- readr::read_rds("data-raw/RDS/LTHUAB2001.rds")
# LTHUAB2002 <- readr::read_rds("data-raw/RDS/LTHUAB2002.rds")
# LTHUAB2003 <- readr::read_rds("data-raw/RDS/LTHUAB2003.rds")
# LTHUAB2004 <- readr::read_rds("data-raw/RDS/LTHUAB2004.rds")
# LTHUAB2005 <- readr::read_rds("data-raw/RDS/LTHUAB2005.rds")
# LTHUAB2006 <- readr::read_rds("data-raw/RDS/LTHUAB2006.rds")
# LTHUAB2007 <- readr::read_rds("data-raw/RDS/LTHUAB2007.rds")
#
# usethis::use_data(LTHUAB1401, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1402, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1403, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1404, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1405, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1406, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1407, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1408, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1409, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1410, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1411, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1412, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1501, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1502, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1503, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1504, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1505, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1506, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1507, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1508, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1509, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1510, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1511, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1512, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1601, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1602, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1603, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1604, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1605, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1606, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1607, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1608, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1609, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1610, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1611, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1612, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1701, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1702, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1703, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1704, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1705, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1706, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1707, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1708, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1709, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1710, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1711, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1712, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1801, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1802, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1803, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1804, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1805, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1806, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1807, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1808, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1809, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1810, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1811, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1812, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1901, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1902, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1903, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1904, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1905, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1906, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1907, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1908, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1909, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1910, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1911, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB1912, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2001, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2002, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2003, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2004, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2005, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2006, overwrite = TRUE, compress = "xz")
# usethis::use_data(LTHUAB2007, overwrite = TRUE, compress = "xz")
#
# # PA
# PAHUAB1401 <- readr::read_rds("data-raw/RDS/PAHUAB1401.rds")
# PAHUAB1402 <- readr::read_rds("data-raw/RDS/PAHUAB1402.rds")
# PAHUAB1403 <- readr::read_rds("data-raw/RDS/PAHUAB1403.rds")
# PAHUAB1404 <- readr::read_rds("data-raw/RDS/PAHUAB1404.rds")
# PAHUAB1405 <- readr::read_rds("data-raw/RDS/PAHUAB1405.rds")
# PAHUAB1406 <- readr::read_rds("data-raw/RDS/PAHUAB1406.rds")
# PAHUAB1407 <- readr::read_rds("data-raw/RDS/PAHUAB1407.rds")
# PAHUAB1408 <- readr::read_rds("data-raw/RDS/PAHUAB1408.rds")
# PAHUAB1409 <- readr::read_rds("data-raw/RDS/PAHUAB1409.rds")
# PAHUAB1410 <- readr::read_rds("data-raw/RDS/PAHUAB1410.rds")
# PAHUAB1411 <- readr::read_rds("data-raw/RDS/PAHUAB1411.rds")
# PAHUAB1412 <- readr::read_rds("data-raw/RDS/PAHUAB1412.rds")
# PAHUAB1501 <- readr::read_rds("data-raw/RDS/PAHUAB1501.rds")
# PAHUAB1502 <- readr::read_rds("data-raw/RDS/PAHUAB1502.rds")
# PAHUAB1503 <- readr::read_rds("data-raw/RDS/PAHUAB1503.rds")
# PAHUAB1504 <- readr::read_rds("data-raw/RDS/PAHUAB1504.rds")
# PAHUAB1505 <- readr::read_rds("data-raw/RDS/PAHUAB1505.rds")
# PAHUAB1506 <- readr::read_rds("data-raw/RDS/PAHUAB1506.rds")
# PAHUAB1507 <- readr::read_rds("data-raw/RDS/PAHUAB1507.rds")
# PAHUAB1508 <- readr::read_rds("data-raw/RDS/PAHUAB1508.rds")
# PAHUAB1509 <- readr::read_rds("data-raw/RDS/PAHUAB1509.rds")
# PAHUAB1510 <- readr::read_rds("data-raw/RDS/PAHUAB1510.rds")
# PAHUAB1511 <- readr::read_rds("data-raw/RDS/PAHUAB1511.rds")
# PAHUAB1512 <- readr::read_rds("data-raw/RDS/PAHUAB1512.rds")
# PAHUAB1601 <- readr::read_rds("data-raw/RDS/PAHUAB1601.rds")
# PAHUAB1602 <- readr::read_rds("data-raw/RDS/PAHUAB1602.rds")
# PAHUAB1603 <- readr::read_rds("data-raw/RDS/PAHUAB1603.rds")
# PAHUAB1604 <- readr::read_rds("data-raw/RDS/PAHUAB1604.rds")
# PAHUAB1605 <- readr::read_rds("data-raw/RDS/PAHUAB1605.rds")
# PAHUAB1606 <- readr::read_rds("data-raw/RDS/PAHUAB1606.rds")
# PAHUAB1607 <- readr::read_rds("data-raw/RDS/PAHUAB1607.rds")
# PAHUAB1608 <- readr::read_rds("data-raw/RDS/PAHUAB1608.rds")
# PAHUAB1609 <- readr::read_rds("data-raw/RDS/PAHUAB1609.rds")
# PAHUAB1610 <- readr::read_rds("data-raw/RDS/PAHUAB1610.rds")
# PAHUAB1611 <- readr::read_rds("data-raw/RDS/PAHUAB1611.rds")
# PAHUAB1612 <- readr::read_rds("data-raw/RDS/PAHUAB1612.rds")
# PAHUAB1701 <- readr::read_rds("data-raw/RDS/PAHUAB1701.rds")
# PAHUAB1702 <- readr::read_rds("data-raw/RDS/PAHUAB1702.rds")
# PAHUAB1703 <- readr::read_rds("data-raw/RDS/PAHUAB1703.rds")
# PAHUAB1704 <- readr::read_rds("data-raw/RDS/PAHUAB1704.rds")
# PAHUAB1705 <- readr::read_rds("data-raw/RDS/PAHUAB1705.rds")
# PAHUAB1706 <- readr::read_rds("data-raw/RDS/PAHUAB1706.rds")
# PAHUAB1707 <- readr::read_rds("data-raw/RDS/PAHUAB1707.rds")
# PAHUAB1708 <- readr::read_rds("data-raw/RDS/PAHUAB1708.rds")
# PAHUAB1709 <- readr::read_rds("data-raw/RDS/PAHUAB1709.rds")
# PAHUAB1710 <- readr::read_rds("data-raw/RDS/PAHUAB1710.rds")
# PAHUAB1711 <- readr::read_rds("data-raw/RDS/PAHUAB1711.rds")
# PAHUAB1712 <- readr::read_rds("data-raw/RDS/PAHUAB1712.rds")
# PAHUAB1801 <- readr::read_rds("data-raw/RDS/PAHUAB1801.rds")
# PAHUAB1802 <- readr::read_rds("data-raw/RDS/PAHUAB1802.rds")
# PAHUAB1803 <- readr::read_rds("data-raw/RDS/PAHUAB1803.rds")
# PAHUAB1804 <- readr::read_rds("data-raw/RDS/PAHUAB1804.rds")
# PAHUAB1805 <- readr::read_rds("data-raw/RDS/PAHUAB1805.rds")
# PAHUAB1806 <- readr::read_rds("data-raw/RDS/PAHUAB1806.rds")
# PAHUAB1807 <- readr::read_rds("data-raw/RDS/PAHUAB1807.rds")
# PAHUAB1808 <- readr::read_rds("data-raw/RDS/PAHUAB1808.rds")
# PAHUAB1809 <- readr::read_rds("data-raw/RDS/PAHUAB1809.rds")
# PAHUAB1810 <- readr::read_rds("data-raw/RDS/PAHUAB1810.rds")
# PAHUAB1811 <- readr::read_rds("data-raw/RDS/PAHUAB1811.rds")
# PAHUAB1812 <- readr::read_rds("data-raw/RDS/PAHUAB1812.rds")
# PAHUAB1901 <- readr::read_rds("data-raw/RDS/PAHUAB1901.rds")
# PAHUAB1902 <- readr::read_rds("data-raw/RDS/PAHUAB1902.rds")
# PAHUAB1903 <- readr::read_rds("data-raw/RDS/PAHUAB1903.rds")
# PAHUAB1904 <- readr::read_rds("data-raw/RDS/PAHUAB1904.rds")
# PAHUAB1905 <- readr::read_rds("data-raw/RDS/PAHUAB1905.rds")
# PAHUAB1906 <- readr::read_rds("data-raw/RDS/PAHUAB1906.rds")
# PAHUAB1907 <- readr::read_rds("data-raw/RDS/PAHUAB1907.rds")
# PAHUAB1908 <- readr::read_rds("data-raw/RDS/PAHUAB1908.rds")
# PAHUAB1909 <- readr::read_rds("data-raw/RDS/PAHUAB1909.rds")
# PAHUAB1910 <- readr::read_rds("data-raw/RDS/PAHUAB1910.rds")
# PAHUAB1911 <- readr::read_rds("data-raw/RDS/PAHUAB1911.rds")
# PAHUAB1912 <- readr::read_rds("data-raw/RDS/PAHUAB1912.rds")
# PAHUAB2001 <- readr::read_rds("data-raw/RDS/PAHUAB2001.rds")
# PAHUAB2002 <- readr::read_rds("data-raw/RDS/PAHUAB2002.rds")
# PAHUAB2003 <- readr::read_rds("data-raw/RDS/PAHUAB2003.rds")
# PAHUAB2004 <- readr::read_rds("data-raw/RDS/PAHUAB2004.rds")
# PAHUAB2005 <- readr::read_rds("data-raw/RDS/PAHUAB2005.rds")
# PAHUAB2006 <- readr::read_rds("data-raw/RDS/PAHUAB2006.rds")
#
# usethis::use_data(PAHUAB1401, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1402, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1403, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1404, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1405, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1406, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1407, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1408, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1409, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1410, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1411, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1412, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1501, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1502, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1503, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1504, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1505, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1506, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1507, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1508, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1509, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1510, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1511, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1512, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1601, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1602, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1603, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1604, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1605, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1606, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1607, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1608, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1609, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1610, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1611, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1612, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1701, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1702, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1703, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1704, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1705, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1706, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1707, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1708, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1709, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1710, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1711, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1712, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1801, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1802, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1803, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1804, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1805, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1806, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1807, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1808, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1809, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1810, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1811, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1812, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1901, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1902, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1903, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1904, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1905, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1906, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1907, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1908, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1909, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1910, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1911, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB1912, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB2001, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB2002, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB2003, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB2004, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB2005, overwrite = TRUE, compress = "xz")
# usethis::use_data(PAHUAB2006, overwrite = TRUE, compress = "xz")
#
# # PF
# PFHUAB1401 <- readr::read_rds("data-raw/RDS/PFHUAB1401.rds")
# PFHUAB1402 <- readr::read_rds("data-raw/RDS/PFHUAB1402.rds")
# PFHUAB1403 <- readr::read_rds("data-raw/RDS/PFHUAB1403.rds")
# PFHUAB1404 <- readr::read_rds("data-raw/RDS/PFHUAB1404.rds")
# PFHUAB1405 <- readr::read_rds("data-raw/RDS/PFHUAB1405.rds")
# PFHUAB1406 <- readr::read_rds("data-raw/RDS/PFHUAB1406.rds")
# PFHUAB1407 <- readr::read_rds("data-raw/RDS/PFHUAB1407.rds")
# PFHUAB1408 <- readr::read_rds("data-raw/RDS/PFHUAB1408.rds")
# PFHUAB1409 <- readr::read_rds("data-raw/RDS/PFHUAB1409.rds")
# PFHUAB1410 <- readr::read_rds("data-raw/RDS/PFHUAB1410.rds")
# PFHUAB1411 <- readr::read_rds("data-raw/RDS/PFHUAB1411.rds")
# PFHUAB1412 <- readr::read_rds("data-raw/RDS/PFHUAB1412.rds")
# PFHUAB1501 <- readr::read_rds("data-raw/RDS/PFHUAB1501.rds")
# PFHUAB1502 <- readr::read_rds("data-raw/RDS/PFHUAB1502.rds")
# PFHUAB1503 <- readr::read_rds("data-raw/RDS/PFHUAB1503.rds")
# PFHUAB1504 <- readr::read_rds("data-raw/RDS/PFHUAB1504.rds")
# PFHUAB1505 <- readr::read_rds("data-raw/RDS/PFHUAB1505.rds")
# PFHUAB1506 <- readr::read_rds("data-raw/RDS/PFHUAB1506.rds")
# PFHUAB1507 <- readr::read_rds("data-raw/RDS/PFHUAB1507.rds")
# PFHUAB1508 <- readr::read_rds("data-raw/RDS/PFHUAB1508.rds")
# PFHUAB1509 <- readr::read_rds("data-raw/RDS/PFHUAB1509.rds")
# PFHUAB1510 <- readr::read_rds("data-raw/RDS/PFHUAB1510.rds")
# PFHUAB1511 <- readr::read_rds("data-raw/RDS/PFHUAB1511.rds")
# PFHUAB1512 <- readr::read_rds("data-raw/RDS/PFHUAB1512.rds")
# PFHUAB1601 <- readr::read_rds("data-raw/RDS/PFHUAB1601.rds")
# PFHUAB1602 <- readr::read_rds("data-raw/RDS/PFHUAB1602.rds")
# PFHUAB1603 <- readr::read_rds("data-raw/RDS/PFHUAB1603.rds")
# PFHUAB1604 <- readr::read_rds("data-raw/RDS/PFHUAB1604.rds")
# PFHUAB1605 <- readr::read_rds("data-raw/RDS/PFHUAB1605.rds")
# PFHUAB1606 <- readr::read_rds("data-raw/RDS/PFHUAB1606.rds")
# PFHUAB1607 <- readr::read_rds("data-raw/RDS/PFHUAB1607.rds")
# PFHUAB1608 <- readr::read_rds("data-raw/RDS/PFHUAB1608.rds")
# PFHUAB1609 <- readr::read_rds("data-raw/RDS/PFHUAB1609.rds")
# PFHUAB1610 <- readr::read_rds("data-raw/RDS/PFHUAB1610.rds")
# PFHUAB1611 <- readr::read_rds("data-raw/RDS/PFHUAB1611.rds")
# PFHUAB1612 <- readr::read_rds("data-raw/RDS/PFHUAB1612.rds")
# PFHUAB1701 <- readr::read_rds("data-raw/RDS/PFHUAB1701.rds")
# PFHUAB1702 <- readr::read_rds("data-raw/RDS/PFHUAB1702.rds")
# PFHUAB1703 <- readr::read_rds("data-raw/RDS/PFHUAB1703.rds")
# PFHUAB1704 <- readr::read_rds("data-raw/RDS/PFHUAB1704.rds")
# PFHUAB1705 <- readr::read_rds("data-raw/RDS/PFHUAB1705.rds")
# PFHUAB1706 <- readr::read_rds("data-raw/RDS/PFHUAB1706.rds")
# PFHUAB1707 <- readr::read_rds("data-raw/RDS/PFHUAB1707.rds")
# PFHUAB1708 <- readr::read_rds("data-raw/RDS/PFHUAB1708.rds")
# PFHUAB1709 <- readr::read_rds("data-raw/RDS/PFHUAB1709.rds")
# PFHUAB1710 <- readr::read_rds("data-raw/RDS/PFHUAB1710.rds")
# PFHUAB1711 <- readr::read_rds("data-raw/RDS/PFHUAB1711.rds")
# PFHUAB1712 <- readr::read_rds("data-raw/RDS/PFHUAB1712.rds")
# PFHUAB1801 <- readr::read_rds("data-raw/RDS/PFHUAB1801.rds")
# PFHUAB1802 <- readr::read_rds("data-raw/RDS/PFHUAB1802.rds")
# PFHUAB1803 <- readr::read_rds("data-raw/RDS/PFHUAB1803.rds")
# PFHUAB1804 <- readr::read_rds("data-raw/RDS/PFHUAB1804.rds")
# PFHUAB1805 <- readr::read_rds("data-raw/RDS/PFHUAB1805.rds")
# PFHUAB1806 <- readr::read_rds("data-raw/RDS/PFHUAB1806.rds")
# PFHUAB1807 <- readr::read_rds("data-raw/RDS/PFHUAB1807.rds")
# PFHUAB1808 <- readr::read_rds("data-raw/RDS/PFHUAB1808.rds")
# PFHUAB1809 <- readr::read_rds("data-raw/RDS/PFHUAB1809.rds")
# PFHUAB1810 <- readr::read_rds("data-raw/RDS/PFHUAB1810.rds")
# PFHUAB1811 <- readr::read_rds("data-raw/RDS/PFHUAB1811.rds")
# PFHUAB1812 <- readr::read_rds("data-raw/RDS/PFHUAB1812.rds")
# PFHUAB1901 <- readr::read_rds("data-raw/RDS/PFHUAB1901.rds")
# PFHUAB1902 <- readr::read_rds("data-raw/RDS/PFHUAB1902.rds")
# PFHUAB1903 <- readr::read_rds("data-raw/RDS/PFHUAB1903.rds")
# PFHUAB1904 <- readr::read_rds("data-raw/RDS/PFHUAB1904.rds")
# PFHUAB1905 <- readr::read_rds("data-raw/RDS/PFHUAB1905.rds")
# PFHUAB1906 <- readr::read_rds("data-raw/RDS/PFHUAB1906.rds")
# PFHUAB1907 <- readr::read_rds("data-raw/RDS/PFHUAB1907.rds")
# PFHUAB1908 <- readr::read_rds("data-raw/RDS/PFHUAB1908.rds")
# PFHUAB1909 <- readr::read_rds("data-raw/RDS/PFHUAB1909.rds")
# PFHUAB1910 <- readr::read_rds("data-raw/RDS/PFHUAB1910.rds")
# PFHUAB1911 <- readr::read_rds("data-raw/RDS/PFHUAB1911.rds")
# PFHUAB1912 <- readr::read_rds("data-raw/RDS/PFHUAB1912.rds")
# PFHUAB2001 <- readr::read_rds("data-raw/RDS/PFHUAB2001.rds")
# PFHUAB2002 <- readr::read_rds("data-raw/RDS/PFHUAB2002.rds")
# PFHUAB2003 <- readr::read_rds("data-raw/RDS/PFHUAB2003.rds")
# PFHUAB2004 <- readr::read_rds("data-raw/RDS/PFHUAB2004.rds")
# PFHUAB2005 <- readr::read_rds("data-raw/RDS/PFHUAB2005.rds")
# PFHUAB2006 <- readr::read_rds("data-raw/RDS/PFHUAB2006.rds")
# PFHUAB2007 <- readr::read_rds("data-raw/RDS/PFHUAB2007.rds")
#
# usethis::use_data(PFHUAB1401, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1402, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1403, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1404, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1405, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1406, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1407, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1408, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1409, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1410, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1411, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1412, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1501, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1502, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1503, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1504, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1505, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1506, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1507, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1508, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1509, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1510, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1511, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1512, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1601, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1602, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1603, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1604, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1605, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1606, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1607, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1608, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1609, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1610, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1611, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1612, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1701, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1702, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1703, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1704, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1705, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1706, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1707, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1708, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1709, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1710, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1711, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1712, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1801, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1802, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1803, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1804, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1805, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1806, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1807, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1808, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1809, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1810, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1811, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1812, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1901, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1902, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1903, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1904, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1905, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1906, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1907, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1908, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1909, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1910, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1911, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB1912, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2001, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2002, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2003, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2004, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2005, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2006, overwrite = TRUE, compress = "xz")
# usethis::use_data(PFHUAB2007, overwrite = TRUE, compress = "xz")
#
# # RD
# RDHUAB1401 <- readr::read_rds("data-raw/RDS/RDHUAB1401.rds")
# RDHUAB1402 <- readr::read_rds("data-raw/RDS/RDHUAB1402.rds")
# RDHUAB1403 <- readr::read_rds("data-raw/RDS/RDHUAB1403.rds")
# RDHUAB1404 <- readr::read_rds("data-raw/RDS/RDHUAB1404.rds")
# RDHUAB1405 <- readr::read_rds("data-raw/RDS/RDHUAB1405.rds")
# RDHUAB1406 <- readr::read_rds("data-raw/RDS/RDHUAB1406.rds")
# RDHUAB1407 <- readr::read_rds("data-raw/RDS/RDHUAB1407.rds")
# RDHUAB1408 <- readr::read_rds("data-raw/RDS/RDHUAB1408.rds")
# RDHUAB1409 <- readr::read_rds("data-raw/RDS/RDHUAB1409.rds")
# RDHUAB1410 <- readr::read_rds("data-raw/RDS/RDHUAB1410.rds")
# RDHUAB1411 <- readr::read_rds("data-raw/RDS/RDHUAB1411.rds")
# RDHUAB1412 <- readr::read_rds("data-raw/RDS/RDHUAB1412.rds")
# RDHUAB1501 <- readr::read_rds("data-raw/RDS/RDHUAB1501.rds")
# RDHUAB1502 <- readr::read_rds("data-raw/RDS/RDHUAB1502.rds")
# RDHUAB1503 <- readr::read_rds("data-raw/RDS/RDHUAB1503.rds")
# RDHUAB1504 <- readr::read_rds("data-raw/RDS/RDHUAB1504.rds")
# RDHUAB1505 <- readr::read_rds("data-raw/RDS/RDHUAB1505.rds")
# RDHUAB1506 <- readr::read_rds("data-raw/RDS/RDHUAB1506.rds")
# RDHUAB1507 <- readr::read_rds("data-raw/RDS/RDHUAB1507.rds")
# RDHUAB1508 <- readr::read_rds("data-raw/RDS/RDHUAB1508.rds")
# RDHUAB1509 <- readr::read_rds("data-raw/RDS/RDHUAB1509.rds")
# RDHUAB1510 <- readr::read_rds("data-raw/RDS/RDHUAB1510.rds")
# RDHUAB1511 <- readr::read_rds("data-raw/RDS/RDHUAB1511.rds")
# RDHUAB1512 <- readr::read_rds("data-raw/RDS/RDHUAB1512.rds")
# RDHUAB1601 <- readr::read_rds("data-raw/RDS/RDHUAB1601.rds")
# RDHUAB1602 <- readr::read_rds("data-raw/RDS/RDHUAB1602.rds")
# RDHUAB1603 <- readr::read_rds("data-raw/RDS/RDHUAB1603.rds")
# RDHUAB1604 <- readr::read_rds("data-raw/RDS/RDHUAB1604.rds")
# RDHUAB1605 <- readr::read_rds("data-raw/RDS/RDHUAB1605.rds")
# RDHUAB1606 <- readr::read_rds("data-raw/RDS/RDHUAB1606.rds")
# RDHUAB1607 <- readr::read_rds("data-raw/RDS/RDHUAB1607.rds")
# RDHUAB1608 <- readr::read_rds("data-raw/RDS/RDHUAB1608.rds")
# RDHUAB1609 <- readr::read_rds("data-raw/RDS/RDHUAB1609.rds")
# RDHUAB1610 <- readr::read_rds("data-raw/RDS/RDHUAB1610.rds")
# RDHUAB1611 <- readr::read_rds("data-raw/RDS/RDHUAB1611.rds")
# RDHUAB1612 <- readr::read_rds("data-raw/RDS/RDHUAB1612.rds")
# RDHUAB1701 <- readr::read_rds("data-raw/RDS/RDHUAB1701.rds")
# RDHUAB1702 <- readr::read_rds("data-raw/RDS/RDHUAB1702.rds")
# RDHUAB1703 <- readr::read_rds("data-raw/RDS/RDHUAB1703.rds")
# RDHUAB1704 <- readr::read_rds("data-raw/RDS/RDHUAB1704.rds")
# RDHUAB1705 <- readr::read_rds("data-raw/RDS/RDHUAB1705.rds")
# RDHUAB1706 <- readr::read_rds("data-raw/RDS/RDHUAB1706.rds")
# RDHUAB1707 <- readr::read_rds("data-raw/RDS/RDHUAB1707.rds")
# RDHUAB1708 <- readr::read_rds("data-raw/RDS/RDHUAB1708.rds")
# RDHUAB1709 <- readr::read_rds("data-raw/RDS/RDHUAB1709.rds")
# RDHUAB1710 <- readr::read_rds("data-raw/RDS/RDHUAB1710.rds")
# RDHUAB1711 <- readr::read_rds("data-raw/RDS/RDHUAB1711.rds")
# RDHUAB1712 <- readr::read_rds("data-raw/RDS/RDHUAB1712.rds")
# RDHUAB1801 <- readr::read_rds("data-raw/RDS/RDHUAB1801.rds")
# RDHUAB1802 <- readr::read_rds("data-raw/RDS/RDHUAB1802.rds")
# RDHUAB1803 <- readr::read_rds("data-raw/RDS/RDHUAB1803.rds")
# RDHUAB1804 <- readr::read_rds("data-raw/RDS/RDHUAB1804.rds")
# RDHUAB1805 <- readr::read_rds("data-raw/RDS/RDHUAB1805.rds")
# RDHUAB1806 <- readr::read_rds("data-raw/RDS/RDHUAB1806.rds")
# RDHUAB1807 <- readr::read_rds("data-raw/RDS/RDHUAB1807.rds")
# RDHUAB1808 <- readr::read_rds("data-raw/RDS/RDHUAB1808.rds")
# RDHUAB1809 <- readr::read_rds("data-raw/RDS/RDHUAB1809.rds")
# RDHUAB1810 <- readr::read_rds("data-raw/RDS/RDHUAB1810.rds")
# RDHUAB1811 <- readr::read_rds("data-raw/RDS/RDHUAB1811.rds")
# RDHUAB1812 <- readr::read_rds("data-raw/RDS/RDHUAB1812.rds")
# RDHUAB1901 <- readr::read_rds("data-raw/RDS/RDHUAB1901.rds")
# RDHUAB1902 <- readr::read_rds("data-raw/RDS/RDHUAB1902.rds")
# RDHUAB1903 <- readr::read_rds("data-raw/RDS/RDHUAB1903.rds")
# RDHUAB1904 <- readr::read_rds("data-raw/RDS/RDHUAB1904.rds")
# RDHUAB1905 <- readr::read_rds("data-raw/RDS/RDHUAB1905.rds")
# RDHUAB1906 <- readr::read_rds("data-raw/RDS/RDHUAB1906.rds")
# RDHUAB1907 <- readr::read_rds("data-raw/RDS/RDHUAB1907.rds")
# RDHUAB1908 <- readr::read_rds("data-raw/RDS/RDHUAB1908.rds")
# RDHUAB1909 <- readr::read_rds("data-raw/RDS/RDHUAB1909.rds")
# RDHUAB1910 <- readr::read_rds("data-raw/RDS/RDHUAB1910.rds")
# RDHUAB1911 <- readr::read_rds("data-raw/RDS/RDHUAB1911.rds")
# RDHUAB1912 <- readr::read_rds("data-raw/RDS/RDHUAB1912.rds")
# RDHUAB2001 <- readr::read_rds("data-raw/RDS/RDHUAB2001.rds")
# RDHUAB2002 <- readr::read_rds("data-raw/RDS/RDHUAB2002.rds")
# RDHUAB2003 <- readr::read_rds("data-raw/RDS/RDHUAB2003.rds")
# RDHUAB2004 <- readr::read_rds("data-raw/RDS/RDHUAB2004.rds")
# RDHUAB2005 <- readr::read_rds("data-raw/RDS/RDHUAB2005.rds")
# RDHUAB2006 <- readr::read_rds("data-raw/RDS/RDHUAB2006.rds")
#
# usethis::use_data(RDHUAB1401, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1402, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1403, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1404, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1405, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1406, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1407, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1408, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1409, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1410, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1411, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1412, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1501, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1502, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1503, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1504, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1505, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1506, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1507, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1508, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1509, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1510, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1511, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1512, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1601, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1602, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1603, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1604, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1605, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1606, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1607, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1608, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1609, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1610, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1611, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1612, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1701, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1702, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1703, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1704, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1705, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1706, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1707, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1708, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1709, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1710, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1711, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1712, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1801, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1802, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1803, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1804, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1805, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1806, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1807, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1808, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1809, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1810, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1811, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1812, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1901, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1902, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1903, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1904, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1905, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1906, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1907, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1908, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1909, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1910, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1911, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB1912, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB2001, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB2002, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB2003, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB2004, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB2005, overwrite = TRUE, compress = "xz")
# usethis::use_data(RDHUAB2006, overwrite = TRUE, compress = "xz")
#
# # SP
# SPHUAB1401 <- readr::read_rds("data-raw/RDS/SPHUAB1401.rds")
# SPHUAB1402 <- readr::read_rds("data-raw/RDS/SPHUAB1402.rds")
# SPHUAB1403 <- readr::read_rds("data-raw/RDS/SPHUAB1403.rds")
# SPHUAB1404 <- readr::read_rds("data-raw/RDS/SPHUAB1404.rds")
# SPHUAB1405 <- readr::read_rds("data-raw/RDS/SPHUAB1405.rds")
# SPHUAB1406 <- readr::read_rds("data-raw/RDS/SPHUAB1406.rds")
# SPHUAB1407 <- readr::read_rds("data-raw/RDS/SPHUAB1407.rds")
# SPHUAB1408 <- readr::read_rds("data-raw/RDS/SPHUAB1408.rds")
# SPHUAB1409 <- readr::read_rds("data-raw/RDS/SPHUAB1409.rds")
# SPHUAB1410 <- readr::read_rds("data-raw/RDS/SPHUAB1410.rds")
# SPHUAB1411 <- readr::read_rds("data-raw/RDS/SPHUAB1411.rds")
# SPHUAB1412 <- readr::read_rds("data-raw/RDS/SPHUAB1412.rds")
# SPHUAB1501 <- readr::read_rds("data-raw/RDS/SPHUAB1501.rds")
# SPHUAB1502 <- readr::read_rds("data-raw/RDS/SPHUAB1502.rds")
# SPHUAB1503 <- readr::read_rds("data-raw/RDS/SPHUAB1503.rds")
# SPHUAB1504 <- readr::read_rds("data-raw/RDS/SPHUAB1504.rds")
# SPHUAB1505 <- readr::read_rds("data-raw/RDS/SPHUAB1505.rds")
# SPHUAB1506 <- readr::read_rds("data-raw/RDS/SPHUAB1506.rds")
# SPHUAB1507 <- readr::read_rds("data-raw/RDS/SPHUAB1507.rds")
# SPHUAB1508 <- readr::read_rds("data-raw/RDS/SPHUAB1508.rds")
# SPHUAB1509 <- readr::read_rds("data-raw/RDS/SPHUAB1509.rds")
# SPHUAB1510 <- readr::read_rds("data-raw/RDS/SPHUAB1510.rds")
# SPHUAB1511 <- readr::read_rds("data-raw/RDS/SPHUAB1511.rds")
# SPHUAB1512 <- readr::read_rds("data-raw/RDS/SPHUAB1512.rds")
# SPHUAB1601 <- readr::read_rds("data-raw/RDS/SPHUAB1601.rds")
# SPHUAB1602 <- readr::read_rds("data-raw/RDS/SPHUAB1602.rds")
# SPHUAB1603 <- readr::read_rds("data-raw/RDS/SPHUAB1603.rds")
# SPHUAB1604 <- readr::read_rds("data-raw/RDS/SPHUAB1604.rds")
# SPHUAB1605 <- readr::read_rds("data-raw/RDS/SPHUAB1605.rds")
# SPHUAB1606 <- readr::read_rds("data-raw/RDS/SPHUAB1606.rds")
# SPHUAB1607 <- readr::read_rds("data-raw/RDS/SPHUAB1607.rds")
# SPHUAB1608 <- readr::read_rds("data-raw/RDS/SPHUAB1608.rds")
# SPHUAB1609 <- readr::read_rds("data-raw/RDS/SPHUAB1609.rds")
# SPHUAB1610 <- readr::read_rds("data-raw/RDS/SPHUAB1610.rds")
# SPHUAB1611 <- readr::read_rds("data-raw/RDS/SPHUAB1611.rds")
# SPHUAB1612 <- readr::read_rds("data-raw/RDS/SPHUAB1612.rds")
# SPHUAB1701 <- readr::read_rds("data-raw/RDS/SPHUAB1701.rds")
# SPHUAB1702 <- readr::read_rds("data-raw/RDS/SPHUAB1702.rds")
# SPHUAB1703 <- readr::read_rds("data-raw/RDS/SPHUAB1703.rds")
# SPHUAB1704 <- readr::read_rds("data-raw/RDS/SPHUAB1704.rds")
# SPHUAB1705 <- readr::read_rds("data-raw/RDS/SPHUAB1705.rds")
# SPHUAB1706 <- readr::read_rds("data-raw/RDS/SPHUAB1706.rds")
# SPHUAB1707 <- readr::read_rds("data-raw/RDS/SPHUAB1707.rds")
# SPHUAB1708 <- readr::read_rds("data-raw/RDS/SPHUAB1708.rds")
# SPHUAB1709 <- readr::read_rds("data-raw/RDS/SPHUAB1709.rds")
# SPHUAB1710 <- readr::read_rds("data-raw/RDS/SPHUAB1710.rds")
# SPHUAB1711 <- readr::read_rds("data-raw/RDS/SPHUAB1711.rds")
# SPHUAB1712 <- readr::read_rds("data-raw/RDS/SPHUAB1712.rds")
# SPHUAB1801 <- readr::read_rds("data-raw/RDS/SPHUAB1801.rds")
# SPHUAB1802 <- readr::read_rds("data-raw/RDS/SPHUAB1802.rds")
# SPHUAB1803 <- readr::read_rds("data-raw/RDS/SPHUAB1803.rds")
# SPHUAB1804 <- readr::read_rds("data-raw/RDS/SPHUAB1804.rds")
# SPHUAB1805 <- readr::read_rds("data-raw/RDS/SPHUAB1805.rds")
# SPHUAB1806 <- readr::read_rds("data-raw/RDS/SPHUAB1806.rds")
# SPHUAB1807 <- readr::read_rds("data-raw/RDS/SPHUAB1807.rds")
# SPHUAB1808 <- readr::read_rds("data-raw/RDS/SPHUAB1808.rds")
# SPHUAB1809 <- readr::read_rds("data-raw/RDS/SPHUAB1809.rds")
# SPHUAB1810 <- readr::read_rds("data-raw/RDS/SPHUAB1810.rds")
# SPHUAB1811 <- readr::read_rds("data-raw/RDS/SPHUAB1811.rds")
# SPHUAB1812 <- readr::read_rds("data-raw/RDS/SPHUAB1812.rds")
# SPHUAB1901 <- readr::read_rds("data-raw/RDS/SPHUAB1901.rds")
# SPHUAB1902 <- readr::read_rds("data-raw/RDS/SPHUAB1902.rds")
# SPHUAB1903 <- readr::read_rds("data-raw/RDS/SPHUAB1903.rds")
# SPHUAB1904 <- readr::read_rds("data-raw/RDS/SPHUAB1904.rds")
# SPHUAB1905 <- readr::read_rds("data-raw/RDS/SPHUAB1905.rds")
# SPHUAB1906 <- readr::read_rds("data-raw/RDS/SPHUAB1906.rds")
# SPHUAB1907 <- readr::read_rds("data-raw/RDS/SPHUAB1907.rds")
# SPHUAB1908 <- readr::read_rds("data-raw/RDS/SPHUAB1908.rds")
# SPHUAB1909 <- readr::read_rds("data-raw/RDS/SPHUAB1909.rds")
# SPHUAB1910 <- readr::read_rds("data-raw/RDS/SPHUAB1910.rds")
# SPHUAB1911 <- readr::read_rds("data-raw/RDS/SPHUAB1911.rds")
# SPHUAB1912 <- readr::read_rds("data-raw/RDS/SPHUAB1912.rds")
# SPHUAB2001 <- readr::read_rds("data-raw/RDS/SPHUAB2001.rds")
# SPHUAB2002 <- readr::read_rds("data-raw/RDS/SPHUAB2002.rds")
# SPHUAB2003 <- readr::read_rds("data-raw/RDS/SPHUAB2003.rds")
# SPHUAB2004 <- readr::read_rds("data-raw/RDS/SPHUAB2004.rds")
# SPHUAB2005 <- readr::read_rds("data-raw/RDS/SPHUAB2005.rds")
# SPHUAB2006 <- readr::read_rds("data-raw/RDS/SPHUAB2006.rds")
#
# usethis::use_data(SPHUAB1401, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1402, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1403, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1404, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1405, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1406, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1407, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1408, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1409, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1410, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1411, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1412, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1501, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1502, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1503, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1504, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1505, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1506, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1507, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1508, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1509, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1510, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1511, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1512, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1601, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1602, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1603, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1604, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1605, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1606, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1607, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1608, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1609, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1610, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1611, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1612, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1701, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1702, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1703, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1704, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1705, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1706, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1707, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1708, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1709, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1710, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1711, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1712, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1801, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1802, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1803, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1804, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1805, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1806, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1807, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1808, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1809, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1810, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1811, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1812, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1901, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1902, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1903, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1904, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1905, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1906, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1907, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1908, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1909, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1910, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1911, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB1912, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB2001, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB2002, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB2003, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB2004, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB2005, overwrite = TRUE, compress = "xz")
# usethis::use_data(SPHUAB2006, overwrite = TRUE, compress = "xz")
